

services:
  db:
    image: postgres:14-alpine
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sude123 # BURAYI KENDİ ŞİFRENİZLE DEĞİŞTİRİN
      POSTGRES_DB: StockDb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      stock-net:
        ipv4_address: 192.168.0.100 # Sabit IP'yi koruyoruz
    healthcheck: # Postgres için sağlık kontrolü eklendi
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stock-api
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy # db sağlıklı olana kadar bekle
    # environment bölümü kaldırıldı, böylece appsettings.json (Host=db) kullanılacak
    networks:
      stock-net:

volumes:
  postgres-data:

networks:
  stock-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/24